spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/base-project?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
logging:
  file: D:/work/baseWork/base/logs/mony.log
myConfig:
  accessDirectory: /upload/**
  mappingUrl: D:/work/baseWork/base/upload/