spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.195:3306/tech?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: tech
    password: tech.wh
logging:
  path: D:/work/baseWork/base/logs
  file: D:/work/baseWork/base/mony.log
myConfig:
  accessDirectory: /upload/**
  mappingUrl: D:/work/baseWork/base/upload/